-- 2️⃣ 테이블 생성
CREATE TABLE USER_INFO (
    userId VARCHAR2(50) NOT NULL PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
