-- 2️⃣ 테이블 생성
CREATE TABLE USER_INFO (
    userId VARCHAR2(50) NOT NULL PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 1️⃣ 테이블 생성 (H2에서는 SEGMENT CREATION, STORAGE, TABLESPACE 제거)
CREATE TABLE TNMC_GNRL_MSG_SCRPT (
    MSG_ID VARCHAR(12) NOT NULL,
    AUDIT_ID VARCHAR(15) NOT NULL,
    AUDIT_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, -- SYSDATE 대신 CURRENT_TIMESTAMP 사용
    MSG_CL_CD VARCHAR(4) NOT NULL,
    MSG_NM VARCHAR(200),
    APRV_OP_RSLT_CD VARCHAR(4),
    GNRL_MSG_DESC VARCHAR(4000),
    OPEN_YN VARCHAR(1),
    OPEN_DT VARCHAR(8) NOT NULL,
    RGST_ORG_ID VARCHAR(10),
    PPRR_ID VARCHAR(10) NOT NULL,
    PPRT_DTM VARCHAR(14) NOT NULL,
    GNRL_MSG_ADD_INFO VARCHAR(2000),
    PRIMARY KEY (MSG_ID) -- PRIMARY KEY 직접 선언
);


-- 1️⃣ 테이블 생성 (H2에서는 SEGMENT CREATION, STORAGE, TABLESPACE 제거)
CREATE TABLE TNMC_GNRL_MSG_DTL (
    MSG_ID VARCHAR(12) NOT NULL,
    GNRL_MSG_TYP_CD VARCHAR(4) NOT NULL,
    CARD_SEQ INT NOT NULL, -- NUMBER(2,0) → INT로 변경
    AUDIT_ID VARCHAR(15) NOT NULL,
    AUDIT_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, -- SYSDATE 대신 CURRENT_TIMESTAMP 사용
    MSG_TITLE_NM VARCHAR(60),
    MSG_PHRS VARCHAR(4000),
    BTN_NM1 VARCHAR(34),
    BTN_NM2 VARCHAR(34),
    IMG_FILE_ID BIGINT, -- NUMBER(18,0) → BIGINT로 변경
    ATFIL_ID BIGINT, -- NUMBER(18,0) → BIGINT로 변경
    PPRR_ID VARCHAR(10) NOT NULL,
    PPRT_DTM VARCHAR(14) NOT NULL,
    PRIMARY KEY (MSG_ID, GNRL_MSG_TYP_CD, CARD_SEQ) -- PRIMARY KEY 직접 선언
);

-- 2️⃣ 인덱스 생성 (H2에서는 TABLESPACE 옵션 제거)
CREATE UNIQUE INDEX TNMC_GNRL_MSG_DTL_PK ON TNMC_GNRL_MSG_DTL (MSG_ID, GNRL_MSG_TYP_CD, CARD_SEQ);

